Replay logging
fossas/spectrometer pull request #185
Opened 2021-02-01 17:55 UTC by cnr

This PR introduces "replay logging", i.e., the capability to record and replay effects that are run.

## Effect recording - `Control.Effect.Record`/`Control.Effect.Record.TH`
These additions allow us to record the effect invocations of arbitrary effects into a JSON structure. Any first-order effect can be recorded, i.e., any effect that doesn't use the `m` parameter in the effect constructors.

For example, this is fine:
```hs
data TTY m a where
  ReadTTY :: TTY m String
  WriteTTY :: String -> TTY m ()
```

..but this is not:
```hs
data Alt m a where
  Alt :: m a -> m a -> Alt m a
```

Effects we require a `Recordable` instance, but in general, this can be freely derived with TemplateHaskell via `deriveRecordable` from `Control.Effect.Record.TH`:
```hs
$(deriveRecordable ''TTY)
```

With a `Recordable` instance available, recording an effect is as easy as, e.g., calling `runRecord @TTY`, which produces a `Map Value Value`

## Effect replaying - `Control.Effect.Replay`/`Control.Effect.Replay.TH`
These additions allow us to use the `Map Value Value` we recorded to replay effects.

In addition to a `Recordable` instance, effects we're replaying require a `Replayable` instance, which in general can be freely derived with TemplateHaskell via `deriveReplayable` from `Control.Effect.Replay.TH`

With a `Replayable` instance available, replaying an effect can be done through, e.g., `runReplay @TTY recordedLogs`

2021-02-09 19:18 UTC, scruffystuffs requested changes
Everything looks good.  Only changes needed are in `analyzeMain`.  If possible, I'd like to see logging and diagnostics move out of the `if->then->else` block in that function.  Also, you may want to try rebasing onto the current master.

2021-02-09 19:18 UTC, scruffystuffs commented on src/Effect/ReadFS.hs
> +        pure (res <$ ctx)
Should we move this above the note about never throwing?

2021-02-10 17:41 UTC, cnr commented on src/Strategy/NuGet/Nuspec.hs
> +      projectLicenses = analyzeLicenses (nuspecFile project)
This comes from `pathfinder`, which we're looking to phase out. Eventually we'd like to eliminate `analyzeLicenses` entirely

2021-02-11 01:24 UTC, scruffystuffs approved these changes
This whole PR is awesome!  I'm stoked to have this.

![giphub](https://media2.giphy.com/media/26ufhqlbeuJsUbvDG/giphy-downsized-medium.gif)

2021-02-22 17:56 UTC, merged