Fix parsing loop for req.txt files
fossas/spectrometer pull request #214
Opened 2021-03-24 11:49 UTC by anuccio1

Problem: If a `requirements.txt` file has a line starting with a non-letter/word character, the CLI completely hangs and appears to be stuck in a `Parser` loop.

To recreate this, add a `requirements.txt` file containing the single line: `_depWithUnderscore=1.2.3`, and run `fossa analyze --output`. The CLI will hang, and never exit. 

I am very new to both `Haskell` and `Parser`'s especially, so am not 100% confident that this "fix" doesn't open up any other issues, however I do know that this change fixes the original problem that I discovered

2021-03-24 17:01 UTC, scruffystuffs requested changes
I think we're adding incorrect logic, but the changes are structurally sound.

2021-03-24 22:15 UTC, liftM commented on src/Strategy/Python/Util.hs
> +  identifier = label "identifier" $ (:) <$> (letterOrDigit <|> oneOfSpecial) <*> (concat <$> many identifier_end)
Can one of you link to a piece of documentation for this? (Ideally, add it as a comment too.)

2021-05-06 16:51 UTC, scruffystuffs commented
@anuccio1 can we close this PR/delete the branch in favor of #235?

2021-05-24 20:07 UTC, cnr commented
Going to close this -- the issue was resolved in #235

2021-05-24 20:07 UTC, closed without merging