Parses entry in pod and dependency section correctly when it has enclosed with quotation
fossas/spectrometer pull request #337
Opened 2021-08-19 03:34 UTC by meghfossa

# Overview

It correctly parses when Podlock file has quotations in entry for dependency and pod section.  

## Acceptance criteria

- Parse Entry in Pod correctly when enclosed with quotation
- Parse Entry in Dependency correctly when enclosed with quotation

## Testing plan

- I've included unit tests to of those effect

For reproducible example, 

- Setup simple pod project
- Add `pod 'GoogleUtilities' ` in `Podfile`
- Execute `pod install`
- Analyze Pod project with applied fixes
- Analyze Pod project without applied fixes

## Risks

N/A

## References

Works on https://github.com/fossas/team-analysis/issues/716

## Checklist

- [ ] I added tests for this PR's change (or confirmed tests are not viable).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] I linked this PR to any referenced GitHub issues, if they exist.

2021-08-19 04:41 UTC, cnr requested changes
Now that we know Podfile.lock is valid yaml (see: [these lines in cocoapods' lockfile.rb](https://github.com/CocoaPods/Core/blob/0a0394afabd9c5f0838fc044e1c817024499dace/lib/cocoapods-core/lockfile.rb#L38-L47)), let's replace the hand-rolled megaparsec parser with the usual `Data.Yaml` parser

Using the yaml parser should incidentally resolve the quotes issue, too

2021-08-19 05:32 UTC, meghfossa commented
> Now that we know Podfile.lock is valid yaml (see: [these lines in cocoapods' lockfile.rb](https://github.com/CocoaPods/Core/blob/0a0394afabd9c5f0838fc044e1c817024499dace/lib/cocoapods-core/lockfile.rb#L38-L47)), let's replace the hand-rolled megaparsec parser with the usual `Data.Yaml` parser
> 
> Using the yaml parser should incidentally resolve the quotes issue, too

I agree, and I don't mind addressing this - but this would increase scope of this PR. I don't mind adding tech-debt ticket and refactoring this in secondary PR right after. Trying to get the changes in this pr may introduce additional time delay on rollout.

2021-08-20 01:26 UTC, meghfossa commented
@cnr per request, I've added PR to https://github.com/fossas/spectrometer/pull/340 to use YAML parsing. But I would like to move ahead with this PR first given the time sensitive nature of this. Would you be able to remove request for change, if the sibling PR satisfies your concerns?

2021-08-20 14:47 UTC, cnr approved these changes
LGTM

2021-08-20 16:47 UTC, merged