Adds Swift Analysis for XCode projects (third of many)
fossas/spectrometer pull request #365
Opened 2021-09-12 21:24 UTC by meghfossa

# Overview

Analyzes Swift Dependency when using Xcode with Swift Package Manager.

## Acceptance criteria

- Analyzes Direct and Deep Dependency when Xcode project is using Swift Package Manager.

Limitation:
- It does not identify edges
- It does not classify test or debug dependencies

## Testing plan

Analyze Xcode Project using Swift package manager. 

Example Open Source Repo:
- https://github.com/carson-katri/reddit-swiftui

```
git clone https://github.com/carson-katri/reddit-swiftui
cabal build && cabal test && make fossa
./fossa analyze ./reddit-swiftui -o | jq
```

## Risks

N/A

## References

- Closes https://github.com/fossas/team-analysis/issues/712

## Checklist

- [ ] I added tests for this PR's change (or confirmed tests are not viable).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] I linked this PR to any referenced GitHub issues, if they exist.

2021-09-12 21:27 UTC, meghfossa commented on src/Strategy/SwiftPM.hs
> +findFirstResolvedFileRecursively :: (Has ReadFS sig m, Has Diagnostics sig m) => Path Abs Dir -> m (Maybe (Path Abs File))
I'm not really sure this is the best way to perform: Retrieve first file (named x) from given base directory (y), where file's immediate parent directory is z.

2021-09-12 21:30 UTC, meghfossa commented on src/Strategy/SwiftPM.hs
> +      isValidXCodeProj <- hasSomeSwiftDeps projFile
Not all xcode project use swift pm for dependency management. This is to avoid unnecessary noise from analysis.

2021-09-23 21:55 UTC, zlav requested changes
The tests you wrote are very good and I love that you are testing the ASCII functions as well. I left some comments about function naming and I also had a few questions but overall this looks solid.

One comment I have about testing is that it would be nice if we used an edited example file with deps like `dep-one` (or something clearly for testing) instead of a real-world example. My usual strategy is to use a large real-world example file (like the one you have) to validate that the parser succeeds when reading it, and to check for the existence of a few deps after you prune the dep list in the file. I will also add a file that has all of the extra BS stripped out that only contains the information we care about. This goes a long way towards making the tests a good source of documentation.

2021-09-23 21:55 UTC, zlav commented on src/Strategy/Swift/Xcode/PbxprojParser.hs
> +    Nothing -> fail "could not find, archiveVersion"
[nit] I don't think you need this comma

```suggestion
    Nothing -> fail "could not find archiveVersion"
```

2021-09-23 21:55 UTC, zlav commented on src/Strategy/Swift/Xcode/PbxprojParser.hs
> +(|->) :: AsciiValue -> Text -> Maybe AsciiValue
Why did you make `|->` the operator and not something like `LookupTextFromAsciiDict`?

I don't love my suggestion either and I can see you wanting something concise, but unless there is a reason to use `|->` I think something a little more descriptive would be ideal.

2021-09-24 01:11 UTC, meghfossa commented on docs/strategies/ios/swift.md
> +- Only Xcode project files in ASCII plist format with UTF-8 encoding are supported.
json, xml - but they are extremely rare ~p99.9+. Xcode and code generator tools all produce ascii. It usually happens when someone has intentionally transformed ascii to json/xml.

2021-09-24 01:56 UTC, meghfossa commented
I clearly need to get editor extension for spelling/grammar to keep myself safe from my lazy eye 😄. I've updated and resolved all the comments now.

2021-09-24 05:16 UTC, zlav approved these changes
Looks great!

2021-09-24 22:08 UTC, merged